development:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: gcVbD4dYQYebmgBeH0pPjS8zDGaxzzOHTMJg7q3YvbBAOIypDlaE9AoGB0HdZwjJ

test:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: gcVbD4dYQYebmgBeH0pPjS8zDGaxzzOHTMJg7q3YvbBAOIypDlaE9AoGB0HdZwjJ

qa:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: gcVbD4dYQYebmgBeH0pPjS8zDGaxzzOHTMJg7q3YvbBAOIypDlaE9AoGB0HdZwjJ

production:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: gcVbD4dYQYebmgBeH0pPjS8zDGaxzzOHTMJg7q3YvbBAOIypDlaE9AoGB0HdZwjJ