development:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: LQYGq1unQ5eOmejGzejPLZsD8goHNXLwbRT_578ftPlXQ7avKO2gyxhLNygACxoM

test: &default
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: LQYGq1unQ5eOmejGzejPLZsD8goHNXLwbRT_578ftPlXQ7avKO2gyxhLNygACxoM

qa1:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: LQYGq1unQ5eOmejGzejPLZsD8goHNXLwbRT_578ftPlXQ7avKO2gyxhLNygACxoM

qa2:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: LQYGq1unQ5eOmejGzejPLZsD8goHNXLwbRT_578ftPlXQ7avKO2gyxhLNygACxoM

production:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: LQYGq1unQ5eOmejGzejPLZsD8goHNXLwbRT_578ftPlXQ7avKO2gyxhLNygACxoM