development:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: _HUX_Ey8ox-jI95YjG2Nt6Hi02PQ4xDYXt7KpyQj-_B52FuLsoHdPtuVJ407731Q

test:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: LQYGq1unQ5eOmejGzejPLZsD8goHNXLwbRT_578ftPlXQ7avKO2gyxhLNygACxoM

qa:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: LQYGq1unQ5eOmejGzejPLZsD8goHNXLwbRT_578ftPlXQ7avKO2gyxhLNygACxoM

production:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: _HUX_Ey8ox-jI95YjG2Nt6Hi02PQ4xDYXt7KpyQj-_B52FuLsoHdPtuVJ407731Q