development:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET:

test: &default
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET:

qa1:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET:

qa2:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET:

production:
  WECHAT_APP_ID: wx9a5aa56c40884879
  WECHAT_APP_SECRET: